### PR TITLE
Remove duplicates

### PR DESCRIPTION
**Pull request by maplepy**

### CODE REVIEW

**Review by pharmapsychotic — APPROVED** [review]
Thanks!

**Comment by maplepy** [comment]
I'll check for the others later today if I have time

**Comment by pharmapsychotic** [comment]
Cool! Be sure to sync up, I made a bunch of changes last night and moved the data files around to handle bundling up for PIP install 😀

**Comment by maplepy** [comment]
Yep no problem will pull before making changes :) havent had much time lately but whenever i can i will check out the other files

**Comment by maplepy** [comment]
by the way is there any incidence on caps or not? because if you prefer to keep like `WON` instead of `won` I can do that same for `Vincent Van Gogh` vs `Vincent van Gogh`

**Pull request merged**
